spring:
  main:
    web-application-type: none
    banner-mode: "off"
logging:
  file.name: logs/app.log
  pattern:
    console:
    file: "%d [%t] %-5level %logger{36} - %msg%n"
  level:
    com.tretton37.webdownloader: DEBUG
webdownloader:
  integration:
    connection-timeout-ms: 10000
    read-timeout-s: 60
    write-timeout-s: 60
  base-url: "https://tretton37.com/"
  base-dir: "target/downloads"
